### ISSUE TITLE
[Bug]: sendSignTxn method : error parsing

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/ledger-cli-app#1]
### What happened?

hello

the parsing of the response in sendSignTxn is not correct:

we obtain:
curve: 04
origin: 88
pubkey: ab2302d79c83cdb86ee9f2cc8e65172188db1f865f3cab581b9b807cb33d0d2bbce78ce43bee7e8a8bd9758725e9047c0d29b309d037b2f07408c84bd149413045022100c5869175a739a88b9d2bcabe31951834ec093ea243d653c4db494dc957d2f95d02201f58d865ba3fe6f3cb3d74875a2ad61916538c61c5078edcd9ce561d5d16729b

### What is expected ?

The public key is encoded with curve type, orgin type i.e., encode(pub_key)

Normally, the parsing should give:

pubkey
02000488ab2302d79c83cdb86ee9f2cc8e65172188db1f865f3cab581b9b807cb33d0d2bbce78ce43bee7e8a8bd9758725e9047c0d29b309d037b2f07408c84bd149413045022100d48b893a447e50cbe0ec60749d9118f18ba0e5f9c1b57dcb2133febf6cb6eca802204c5a217fee6634ea5170486451fe1d68dd120597a1ea32458b5ff79f40ef66b99000

curve: 02
origin: 00
pubkey(04XY): 0488ab2302d79c83cdb86ee9f2cc8e65172188db1f865f3cab581b9b807cb33d0d2bbce78ce43bee7e8a8bd9758725e9047c0d29b309d037b2f07408c84bd149413045022100d48b893a447e50cbe0ec60749d9118f18ba0e5f9c1b57dcb2133febf6cb6eca802204c5a217fee6634ea5170486451fe1d68dd120597a1ea32458b5ff79f40ef66b9

Varun precise "We do need the asn signature since that will be used in the field of "previous signature" in the transaction builder."

**Comment by dr-chain** [comment]
@prix-uniris Please look into this and commit latest changes.

**Comment by redDwarf03** [comment]
i propose PR #2
